name: Deploy Angular App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22.5.1'

    - name: Install dependencies
      run: npm install

    - name: Install Angular CLI
      run: npm install -g @angular/cli

    - name: Build Angular app
      run: ng build --configuration production

    - name: Deploy to Hostinger
      env:
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
      run: |
        curl -X POST $WEBHOOK_URL
