name: Build and Deploy Angular App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.5.1'

      - name: Install dependencies
        run: npm install

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Build Angular app
        run: npm run build -- --configuration production

      - name: Archive production artifacts
        run: tar -czvf build-artifacts.tar.gz -C dist .

      - name: Upload production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build-artifacts.tar.gz

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts

      - name: Create deployment directory
        run: mkdir -p deployment

      - name: Move build artifacts to deployment directory
        run: mv build-artifacts.tar.gz deployment/

      - name: Extract build artifacts
        run: tar -xzvf deployment/build-artifacts.tar.gz -C deployment

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add Hostinger host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p 65002 89.117.169.99 >> ~/.ssh/known_hosts

      - name: Secure Copy to Hostinger
        run: scp -P 65002 -r deployment/* u252525807@89.117.169.99:/home/u252525807/public_html/
