name: Deploy Angular App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.5.1'

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm install
          echo "Dependencies installed."

      - name: Install Angular CLI
        run: |
          echo "Installing Angular CLI..."
          npm install -g @angular/cli
          echo "Angular CLI installed."

      - name: Build Angular app
        run: |
          echo "Building Angular app..."
          ng build --configuration production
          echo "Angular app built."

      - name: Check build output
        run: |
          echo "Checking build output..."
          if [ -d "dist" ]; then
            echo "Build succeeded."
            ls -la dist/
          else
            echo "Build failed."
            exit 1
          fi

      - name: Install rsync
        run: sudo apt-get install -y rsync

      - name: Deploy to Hostinger
        if: success()
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: |
          echo "Deploying to Hostinger..."
          rsync -av --delete dist/ /home/uXXXXXX/public_html/
          echo "Deployment completed."
